#!/bin/bash

function get_volume {
    amixer sget Master | tail -1 | awk '$0~/%/{print $5}' | tr -d '[]%'
}

function is_mute {
    amixer get Master | grep '%' | grep -oE '[^ ]+$' | grep off > /dev/null
}

function send_notification {
    volume=`get_volume`
    # Make the bar with the special character ─ (it's not dash -)
    # https://en.wikipedia.org/wiki/Box-drawing_character
    bar=$(seq -s "─" $(($volume / 5)) | sed 's/[0-9]//g')
    # Send the notification
    dunstify -u low -p -r 2593 -i $ICON "$TEXT\n$bar"
}

if [ "$1" == "down" ]
then
 pulseaudio-ctl down
 ICON="/usr/share/icons/Adwaita/16x16/status/audio-volume-low.png"
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f7 | tr -d '[]' )
elif [ "$1" == "up" ]
then
 pulseaudio-ctl up
 ICON="/usr/share/icons/Adwaita/16x16/status/audio-volume-high.png"
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f7 | tr -d '[]' )
elif [ "$1" == "mute" ]
then
 pulseaudio-ctl mute
 TEXT=$(amixer sget Master | tail -1 | cut -d' ' -f8 | tr -d '[]' )
 if [ "$TEXT" == "on" ]
 then
     ICON="/usr/share/icons/Adwaita/16x16/status/audio-volume-high.png"
 else
     ICON="/usr/share/icons/Adwaita/16x16/status/audio-volume-muted.png"
 fi
else
 echo "Usage volume [down | up | mute]\n"
fi

send_notification
