#!/bin/bash
# Because Git submodule commands cannot operate without a work tree, they must
# be run from within $HOME (assuming this is the root of your dotfiles)

cd "$HOME"
mkdir .cache/dein
curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh > .cache/dein/installer.sh
echo "Installing Dein for NeoVim"
bash .cache/dein/installer.sh .local/share/dein
